### ISSUE TITLE
Edit Tasks

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#19]
## Value Proposition
**As a** User
**I need to** edit all my tasks entries
**to be able to** change my task or opinion
## Description
![Bildschirmfoto 2022-05-20 um 10 31 20](https://user-images.githubusercontent.com/101577601/169488052-8ba802d2-02ec-4e84-8bc6-c8911443b167.png)

## Acceptance Criteria
- [x] A Button labeled "Edit" is shown on every task
- [x] It opens a form in the task.
- [x] The form already contains the tasks text, date etc. (Similar to #4 )
- [x] You can save the edits by a button labeled "Save"
- [x] The task is displayed edited on the same place.
## Tasks
- [x] Create a new branch "edit-task"
- [x] Create a Edit Button
- [x] Check if Form from #4 can be used again and use it according to "DRY"
- [x] Toggle Edit Button to edit-form with label "Save" and back to "Edit"
- [ ] Add test to check if data is changed
## Complexity
L

**Comment by raimartontsch** [comment]
HI @HishamAlmannai! 

Looks good so far :) 
Some questions/ideas on this. Are you really toggeling the edit area or is it more like an accordeon feature you are referring to? Are you adding the form component you have already built? If so you could directly name the component you are using here to avoid any misunderstanding. Just in case ;)

**Comment by HishamAlmannai** [comment]
Hi Raimar,

thanks for reviewing. 
It is indeed a toggle. The accordion feature is in another pipeline and shall cover to long tasks as well ;)
Yes, i will try to use the same form again. Detailed it now in the task section.

**Comment by raimartontsch** [comment]
Alright, cool! Thanks for clarifying. I'll give it a Go! in a sec. ;)
