### ISSUE TITLE
View Task

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#2]
## Value Proposition

**As a** User
**I need to** track my Task
**to be able to** see my Task and mark as done

## Description

![Bildschirmfoto 2022-05-05 um 14 35 50](https://user-images.githubusercontent.com/101577601/166924199-ba4088c6-e0ec-4013-882f-716b2d729e86.png)

## Acceptance Criteria

- [ ]  The Task is displayed, labeled by "ToDo:"
- [ ] The Task can be marked as done by a Checkbox

## Tasks

- [ ] Create a new branch "view-task"
- [ ] Create the data structure to hold the Task and Checkbox
- [ ] Create n new component to render the data in a tag
- [ ] The component receives product details via props
- [ ] Add component to the app
- [ ] Add to Storybook
- [ ] Add test to check if data is rendered

## Complexity 
M

**Comment by anitaschiller** [comment]
Hi Hisham,

it sounds a bit as if the possibility to check/uncheck single tasks is part of your user story? I would focus on displaying static data here, so you could add the following to your Acceptance Criteria:

- If a task has already been done, the checkbox should be checked
- If the task is still open, the checkbox should not be checked

instead of 
- The Task can be marked as done by a Checkbox (--> this might be another user story)

Suggestion for an adapted Story:
```
As a User
I need to see a list of my tasks
to be able to get an overview of open todos.
```

**Comment by HishamAlmannai** [comment]
Hi Anita,
thanks for reviewing.
I have updated the user-story and will adjust the second user story to it in a minute.
