### ISSUE TITLE
Visualize Tasks Done

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#22]
## Value Proposition
**As a** User
**I need to** show my done tasks in a graph
**to be able to** see my Progress over a period of time
## Description
![Bildschirmfoto 2022-05-25 um 14 54 40](https://user-images.githubusercontent.com/101577601/170266827-76d634ce-85df-41ad-a88b-ac6e4f3b887d.png)
## Acceptance Criteria
- [ ] A graph shows my done tasks over a period of time
- [ ] The time period is from creation date to now
## Tasks
- [x] Create a new branch "visualize-tasks-done"
- [ ] Create a component for the graph
- [ ] Add timestamp for done/checkbox
- [ ] Add timestamp for create or add startdate
- [ ] Add recharts
- [ ] Link with database between done and time
- [ ] Add to App
- [ ] Add to Storybook
## Complexity
XL
