### ISSUE TITLE
Design app

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#24]
## Value Proposition
**As a** User
**I need to** see a visually pleasing list
**to be able to** enjoy using my app
## Description
![Bildschirmfoto 2022-05-29 um 12 54 43](https://user-images.githubusercontent.com/101577601/170864427-61701f89-d8a9-4c93-9832-70726844b6a2.png)

## Acceptance Criteria
- [ ] Tasks should be displayed as stack of cards
- [ ] All buttons should have the same look
## Tasks
- [x] Create a new branch "design-overhaul"
- [ ] Create necessary styling: 
- [ ] Font sizes are all the same.
- [ ] Design custom checkbox.
- [ ] Set overall variables for font size and colors
- [ ] Make design responsive for desktop and mobile
- [ ] Check Storybook
## Complexity
M

**Comment by F-Kirchhoff** [comment]
Hey Hisham, please specify your 'necessary styling'. Except that its good.

**Comment by HishamAlmannai** [comment]
Thanks, added some.
