### ISSUE TITLE
Add bookmark

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#25]
## Value Proposition
**As a** User
**I need to** bookmark preferred tasks
**to be able to** make a quick selection based on my subjective view
## Description
![Bildschirmfoto 2022-05-29 um 13 08 26](https://user-images.githubusercontent.com/101577601/170864922-ef4a89d2-914f-454d-9312-7ead166ecc35.png)

## Acceptance Criteria
- [ ] Every task should have a invisible bookmark at the right end
- [ ] Only bookmarked cards show the bookmark
- [ ] The design should simulate a folded corner
## Tasks
- [ ] Create a new branch "add-bookmark"
- [ ] Create a button to every task
- [ ] Create a key bookmark to database
- [ ] Link button to toggle database
- [ ] Design bookmark
- [ ] Add to Storybook
- [ ] Add test to check if data is rendered
## Complexity
M

**Comment by F-Kirchhoff** [comment]
LGTM 🚀
