### ISSUE TITLE
Connect to backend

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#26]
## Value Proposition
**As a** User
**I need to** save my data in the backend
**to be able to** use my app on different divices
## Acceptance Criteria
- [ ] The Tasks needs to be accessible over the internet
- [ ] The Tasks need to have the same function able to edit, delete
## Tasks
- [ ] Create a new branch ""
- [ ] Create 
- [ ] Add 
- [ ] Add to Storybook
- [ ] Add test to check if data is rendered
