### ISSUE TITLE
Display Task List

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#3]
## Value Proposition

**As a** User
**I need to** get an Overview of all my tasks
**to be able to** see all my task as a list

## Description
![Bildschirmfoto 2022-05-05 um 14 58 09](https://user-images.githubusercontent.com/101577601/166927734-00a079b9-9465-4cb1-83ac-918fe8e275ff.png)

## Acceptance Criteria
- [ ] Each Task should be visually separated
- [ ] Each Task should display it's own checkbox
- [ ] All Tasks should be displayed in vertical order

## Tasks
- [ ] Create a new branch "display-task-list"
- [ ] Create a database with tasks
- [ ] Create a List-component which renders each task
- [ ] Add the database to the component
- [ ] Add to Storybook
- [ ] Add basic styling
- [ ] Add test to check if data is rendered
## Complexity
S

**Comment by anitaschiller** [comment]
I think your acceptance criteria can still be more precise: e.g. what happens if you click on the text and not on the checkbox; will the text be crossed out if the task is done? Maybe you can think again about all the scenarios that could happen before you start coding.
However, you are ready to go. ✅
