### ISSUE TITLE
Evaluate priority

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#33]
## Value Proposition
**As a** User
**I need to** compare each task with another
**to be able to** order my priority systematically
## Acceptance Criteria
- [ ] Each task should be checked with another by showing only two tasks at a time.
- [ ] One of the two tasks should be chosen as higher priority
- [ ] After all tasks have been compared the tasklist is shown in determined order.
- [ ] The Task with the highest priority is shown at top
## Tasks
- [ ] Create a new branch ""
- [ ] Create 
- [ ] Add 
- [ ] Add to Storybook
- [ ] Add test to check if data is rendered
