### ISSUE TITLE
Create navigation bar

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#34]
## Value Proposition
**As a** User
**I need to** navigate the App by buttons
**to be able to** get to features quickly
## Description
<img width="381" alt="Bildschirmfoto 2022-06-02 um 17 25 18" src="https://user-images.githubusercontent.com/101577601/171667387-3835f9f3-4723-4a35-884e-b4ad6268a28e.png">
## Acceptance Criteria
- [ ] A navigation bar should be at the bottom of the window
- [ ] The Buttons should be displayed as icons
- [ ] The Buttons are Create, Filter, Metrics, Archive
## Tasks
- [ ] Create a new branch "create-navigation-bar"
- [ ] Create icons as svg
- [ ] Create Navbar component
- [ ] Add icons to navbar
- [ ] Link buttons to features
- [ ] Remove  unneccessary buttons from other components
- [ ] Add to Storybook
## Complexity
M

**Comment by F-Kirchhoff** [comment]
Hey Hisham, if these elements link to different pages in your app you should use anchor tags instead of buttons, but you can style them like buttons of course. And you don't need to specify in the userstory 'how' the user navigates, just that he wants an easy way to navigate.
