### ISSUE TITLE
Create Task

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#4]
## Value Proposition
**As a** User
**I need to** add Tasks
**to be able to** create more Tasks
## Description
![Bildschirmfoto 2022-05-05 um 16 02 18](https://user-images.githubusercontent.com/101577601/166940284-da2598a2-f510-4dff-a595-6a73e62f8ed3.png)
## Acceptance Criteria
- [x] A Form with the label "Create" is displayed
- [x] An Input field for the Task is displayed, Labeled inside with "Stop Starting > Start finishing"
- [x] The Input field is mandatory. There is an error message per input field if no value is entered.
- [x] The Input field must be text with 2-200 characters
- [x] A button to save the task, labeled "Save"
- [x] The saving mechanisms checks if the new product already exists. If yes, there is an error message saying "Task already in the list"
- [x] After saving the new task will appear on the top of the list of all products (see #3 ) 
- [x] After saving the input field is cleared
## Tasks
- [x] Create a new branch "create-task"
- [x] Create a new input component 
- [x] Create a new button component 
- [x] Create a form component to render the form
- [x] Add form with input and submit-button
- [x] Mark input field as required
- [x] Add text length validation
- [x] Add the task with a checkbox unchecked to the existing list in the data structure after submitting the form with valid data
- [x] Add to Storybook: Input, button, form
- [ ] #16
- [x] Add test to check if task was added to the data structure
- [x] Add test to check if data is rendered
- [x] Add form component to app
 ## Complexity
XL

**Comment by HishamAlmannai** [comment]
It is not clear if field validation is my area of responsibility. Moved to separate issue in Backlog.
