### ISSUE TITLE
Delete Task

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#5]
## Value Proposition
**As a** User
**I need to** clean up my List
**to be able to** remove a task
## Description
![Bildschirmfoto 2022-05-05 um 16 32 34](https://user-images.githubusercontent.com/101577601/166946686-a18c50cd-8d41-4242-aa1f-8d1a53568db2.png)
## Acceptance Criteria
- [ ] A delete-button for every task is displayed, labeled "Delete Task"
- [ ] The delete-button removes the assigned task from the list
## Tasks
- [ ] Create a new branch "delete-task"
- [ ] Add a button component to the Task component (see #2 ), labled "Delete"
- [ ] Remove specific task from the list after button is clicked.
- [ ] Add test to check if data is modified
## Complexity
M

**Comment by aclaes** [comment]
Hi Hisham,

This is a good user story. There is just one small, but important, point to change. I think you switched the activity and the reason for this action within the value proposition.

Activity: remove a task
Reason: to clean up my list.

**Comment by HishamAlmannai** [comment]
So true. It happens to be a leftover before I asked about it in the lesson.
thx for reviewing
