### ISSUE TITLE
Archive checked Tasks

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#7]
## Value Proposition
**As a** User
**I need to** remove checked tasks from display
**to be able to** clean up my List
## Description
![Bildschirmfoto 2022-05-18 um 15 33 33](https://user-images.githubusercontent.com/101577601/169051313-9dd0b68d-1e55-46d6-b45c-a9b5855581a8.png)
## Acceptance Criteria
- [x] A button is displayed at the end of the Tasklist, labeled "Archive checked"
- [x] The button removes all checked Tasks from display, but doesn't delete the Tasks
## Tasks
- [x] Create a new branch "archived-checked-tasks"
- [x] Create a button
- [x] Create a new category in the database
- [x] Link category with displayed Task
- [x] Link button with the new category
- [x] Add to App
- [x] Add tests to check if specific data is not rendered
## Complexity
M

**Comment by HishamAlmannai** [comment]
I am not sure if a task:
- [ ] Add tests to check if data is still in the database
would make sense. Since a test should simulate user behavior. Comments welcome.

**Comment by PReichetanz** [comment]
> I am not sure if a task:
> 
>     * [ ]  Add tests to check if data is still in the database
> 
> 
> would make sense. Since a test should simulate user behavior. Comments welcome.

I would say no, especially because this would not be a component test.

Your description does not say where this button is displayed, I would add an image to show the entire page with the button.
