### ISSUE TITLE
Collapse Taskview

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#8]
## Value Proposition
**As a** User
**I need to** get an better Overview of my Tasks
**to be able to** reduce Task Information to one row
## Description
![Bildschirmfoto 2022-05-06 um 15 04 16](https://user-images.githubusercontent.com/101577601/167137778-0d30be11-413f-4e20-b9f2-7d4a25935138.png)

## Acceptance Criteria
- [ ] Only the first row of every task should be displayed on default
- [ ] On tap the task should expand to its full length and show the edit and delete button. 
- [ ] The display of the task should be able to toggle in the same manor.
- [ ] When you tap the checkbox the edit or delete button, the task should not toggle
## Tasks
- [ ] Create a new branch "collapse-taskview"
- [ ] Add basic styling
- [ ] Create two versions of the component and install an onClick event listener for toggling the visibility
- [ ] Hand down property to task component
- [ ] Add test to check if data is shown
## Complexity
M

**Comment by HishamAlmannai** [comment]
Thanks for reviewing and the suggestions. I edited it accordingly.
