### ISSUE TITLE
Add due date

### ISSUE THREAD

**Issue by HishamAlmannai** [HishamAlmannai/capstone-project#9]
## Value Proposition
**As a** User
**I need to** add a due date
**to be able to** see when a task is due
## Description
<img width="414" alt="Bildschirmfoto 2022-05-09 um 12 41 20" src="https://user-images.githubusercontent.com/101577601/167394188-beb7726c-a2ad-44c7-833c-d2db38273e7d.png">

## Acceptance Criteria
- [x] A due date is mandatory on creating a task
- [x] A due date has to be displayed on each task
- [ ] ~~Tasks can be sorted by due dates~~ (#6)
## Tasks
- [x] Create a new branch "add-due-date"
- [x] Create a Category Date in the database (#3)
- [x] Add an Inputfield into to the form (#4)
- [x] Link the Inputfield to the database
- [x] Add to Storybook
- [ ] ~~Add a button to sort by date~~ (#6)
- [ ] ~~Add sort-logic~~
- [x] Add test to check if data is saved
- [ ] ~~Add test to check if data is sorted~~
- [ ] Add basic design
## Complexity
L

**Comment by NadineGrosskreuz** [comment]
Hey Hisham,
good work! 🚀 
Just a few things:

I would switch the value proposition like this:
As a user
I need to to add a due date
to be able to see when a task is due.

I think you can remove the first point from your acceptance criteria?
I would write: It should be possible ..

I think it is written "input field".
Maybe you linked to the wrong story at the second task?
